# Generated by Django 4.1.5 on 2023-03-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_sucursales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
