# Generated by Django 4.1.5 on 2023-03-23 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Productos', '0003_delete_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fechaComentario', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fechaComentario'],
            },
        ),
        migrations.DeleteModel(
            name='Sucursales',
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'ordering': ['usuario', '-fechaPublicacion']},
        ),
        migrations.RemoveField(
            model_name='productos',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='seccion',
        ),
        migrations.AddField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='emailContacto',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='fechaPublicacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='imagenProducto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='productos',
            name='marca',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='modelo',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='producto',
            field=models.CharField(choices=[('computadoras', 'Computadoras'), ('laptops', 'Laptops'), ('celulares', 'Celulares'), ('tablets', 'Tablets'), ('televisores', 'Televisores')], default='computadoras', max_length=15),
        ),
        migrations.AddField(
            model_name='productos',
            name='titulo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productos',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='comentario',
            name='comentario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Productos.productos'),
        ),
    ]
