# Generated by Django 4.1.5 on 2023-03-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_comentario_delete_sucursales_alter_productos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagenProducto',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagenes/'),
        ),
    ]
