# Generated by Django 4.1.5 on 2023-03-29 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0010_alter_productos_imagenproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'ordering': ['usuario']},
        ),
        migrations.RemoveField(
            model_name='productos',
            name='fechaPublicacion',
        ),
    ]
