# Generated by Django 4.1.5 on 2023-03-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0011_alter_productos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={},
        ),
        migrations.AddField(
            model_name='productos',
            name='fechaPublicacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
