# Generated by Django 4.1.5 on 2023-03-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0013_alter_productos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='producto',
            field=models.CharField(choices=[('computadora', 'Computadora'), ('laptops', 'Laptops'), ('celulares', 'Celulares'), ('tablets', 'Tablets'), ('televisores', 'Televisores')], default='computadora', max_length=15),
        ),
    ]
